sudo: required

services:
  - docker

env: SH="docker exec -t ubuntu-test bash -c"

before_install:
  - docker run -d --name ubuntu-test -e LC_ALL="en_US.UTF-8" -e LANG="en_US.UTF-8" -v $(pwd):/travis -w /travis ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - $SH "apt-get update"
  - $SH "DEBIAN_FRONTEND=noninteractive apt-get install -y locales"
  - $SH "DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential"
  - $SH "DEBIAN_FRONTEND=noninteractive apt-get install -y git"
  - $SH "DEBIAN_FRONTEND=noninteractive apt-get install -y expect"
  - $SH "locale-gen en_US.UTF-8"
  - $SH "git config --global user.email you@example.com"
  - $SH "git config --global user.name name"

script:
  - $SH "cp config.mk.example config.mk"
  - $SH "make test"
